[#ftl]
[@b.head/]
[#if std ??]
    [@b.toolbar title="${std.name}的帮扶记录"/]
[/#if]
[@b.grid items=records var="record"]
    [@b.gridbar]
        [#if std ??]
          bar.addItem("${b.text("action.new")}",action.add());
          bar.addItem("${b.text("action.modify")}",action.edit());
          bar.addItem("${b.text("action.delete")}",action.remove("确认删除?"));
        [/#if]
    [/@]
    [@b.row]
        [@b.boxcol /]
        [#if std ??]
            [@b.col width="20%" property="record.semester.code" title="学年学期"]${record.semester.schoolYear}年${record.semester.name}学期[/@]
            [@b.col width="20%" property="name" title="帮扶记录"][@b.a href="!info?id=${record.id}" title="查看详情"]${record.name}[/@][/@]
            [@b.col width="15%" property="alertType.name" title="预警类别"/]
            [@b.col width="25%" property="detail" title="预警情况说明" style="white-space:pre"/]
            [@b.col width="15%" property="updatedAt" title="帮扶日期"]${record.updatedAt?string("yyyy-MM-dd")}[/@]
        [#else]
            [@b.col width="10%" property="semester.code" title="学年学期"]${record.semester.schoolYear}年${record.semester.name}学期[/@]
            [@b.col width="10%" property="file.std.code" title="学号"/]
            [@b.col width="10%" property="file.std.name" title="姓名"/]
            [@b.col width="20%" property="file.std.state.squad.name" title="班级"/]
            [@b.col width="15%" property="file.std.state.department.name" title="院系"/]
            [@b.col width="10%" property="alertType.name"  title="预警类别"/]
            [@b.col width="10%" property="name" title="帮扶记录"][@b.a href="!info?id=${record.id}" title="查看详情"]${record.name}[/@][/@]
            [@b.col width="10%" property="updatedAt" title="帮扶日期"]${record.updatedAt?string("yyyy-MM-dd")}[/@]
        [/#if]
    [/@]
[/@]
[@b.foot/]
