[#ftl]
[@b.head/]
[@b.toolbar title="新建/修改统计办法"]bar.addBack();[/@]
[@b.tabs]
  [#assign sa][#if statMethod.persisted]!update?id=${statMethod.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
    [@b.textfield name="statMethod.name" label="名称" value="${statMethod.name!}" required="true"/]
    [@b.textfield name="statMethod.description" label="办法描述" value="${statMethod.description!}" required="true" /]
    [@b.textfield name="statMethod.serviceName" label="办法服务名" value="${statMethod.serviceName!}" required="true" /]
    [@b.radios name="statMethod.enabled" label="是否启用" value=statMethod.enabled /]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
