[#ftl]
[@b.head/]
  [@b.nav class="nav nav-tabs"]
    [@b.navitem href="stat-rule"]统计规则[/@]
    [@b.navitem href="stat-method"]统计办法[/@]
  [/@]
[@b.div id="statMethodSearchDiv" href="!search"/]
[@b.foot/]
