[#ftl]
[@b.head/]
[@b.toolbar title="不及格课程信息"]
    bar.addBack();
[/@]
[#if grades?? && grades?size>0]
    [@b.grid items=grades?sort_by(["semester","beginOn"]) var="grade"]
        [@b.row]
            [@b.col title="序号" width="80px"]${grade_index+1}[/@]
            [@b.col title="开课学期" width="15%"]${grade.semester.schoolYear}学年${grade.semester.name}学期[/@]
            [@b.col property="crn" title="课程序号" width="10%"/]
            [@b.col property="course.code" title="课程代码" width="12%"/]
            [@b.col property="course.name" title="课程名称" /]
            [@b.col property="course.defaultCredits" title="学分" width="10%"]${grade.credits}[/@]
            [@b.col property="score" title="成绩" width="10%"]${(courseGrade.scoreText)?if_exists}[/@]
        [/@]
    [/@]
[#else] 该学生不存在不及格课程
[/#if]
[@b.foot/]
